// Generates a local .env with random secrets. Never overwrites an existing file.
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

if (existsSync(".env")) {
  console.log(".env already exists — leaving it untouched.");
  process.exit(0);
}
const rand = (n) => randomBytes(n).toString("base64url");
const dbPassword = rand(18);
const demoPassword = `${rand(9)}Aa1`;
const contents = `# Generated by scripts/setup-env.mjs — local development only. Never commit this file.
DATABASE_URL="postgresql://opsflow:${dbPassword}@localhost:54329/opsflow"
APP_URL="http://localhost:3000"
# 32 bytes, base64. Encrypts webhook signing secrets at rest.
APP_ENCRYPTION_KEY="${randomBytes(32).toString("base64")}"
# AI provider: "mock" (deterministic, no network) or "claude".
AI_PROVIDER="mock"
# ANTHROPIC_API_KEY=""
# ANTHROPIC_MODEL="claude-sonnet-5"
# Password for the seeded demo user (demo@opsflow.test).
DEMO_USER_PASSWORD="${demoPassword}"
`;
writeFileSync(".env", contents, { mode: 0o600 });
console.log("Created .env");
console.log(`Demo login: demo@opsflow.test / ${demoPassword}`);
